packages:
  - ./app
  - ./cdk

allowBuilds:
  esbuild: false
  sharp: false

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@11.15.1
  - astro@6.4.6 || 7.0.10 || 7.1.0

overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

  aws-cdk-lib: 2.257.0
  astro@>=2.9.0 <=7.0.9: ^7.0.10

trustPolicy: no-downgrade
